#Settings for the application

# Whether to encrypt private keys
private_key_encryption: true

# Number of threads to use for processing wallets
threads: 1

#BY DEFAULT: [0,0] - all wallets
#Example: [2, 6] will run wallets 2,3,4,5,6
#[4,4] will run only wallet 4
range_wallets_to_run: [0,0]

# Whether to shuffle the list of wallets before processing
shuffle_wallets: true

# Working only if range_wallet_to_run = [0,0] 
# BY DEFAULT: [] - all wallets 
# Example: [1, 3, 8] - will run only 1, 3 and 8 wallets
exact_wallets_to_run: []

# Show wallet address in logs
show_wallet_address_logs: false

#Check for github updates
check_git_updates: true

# the log level for the application. Options: DEBUG, INFO, WARNING, ERROR
log_level : INFO

# Delay before running the same wallet again after it has completed all actions (1 - 2 hrs default)
random_pause_wallet_after_completion:
  min: 3600
  max: 7200

# Random pause between wallets in seconds
random_pause_between_wallets:
  min: 5
  max: 60

# Random pause between actions in seconds
random_pause_between_actions:
  min: 5
  max: 30

# Random pause to start wallet in seconds
random_pause_start_wallet:
  min: 0
  max: 60

#OKX api keys
okx_api_key: ''
okx_api_secret: ''
okx_passphrase: ''

#Withdrawal amount in SOL
withdrawal_amount:
  min: 0.8
  max: 1

#Percent for SOL commissions:
sol_balance_for_commissions: 0.05

#Minimal Sol Balance to refill SOL for comission
minimal_sol_balance: 0.005

#Refill Sol for commission in usd
refill_usd_amount:
  min: 8
  max: 10

#Swaps count per cycle on SPOT
swaps_count:
  min: 5
  max: 10

#Invite codes
invite_codes: []